name: Run Data Scripts

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Data Generation Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ATLAS_PUBLIC_KEY: ${{ secrets.ATLAS_PUBLIC_KEY }}
          ATLAS_PRIVATE_KEY: ${{ secrets.ATLAS_PRIVATE_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: python dynamic_data_generation.py

      - name: Run Data Pull Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: python data_pull.py

